const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d');
let clips=[],selected=-1,time=0,playing=false,exporting=false,abort=false,music=null,audioCtx=null,destination=null,musicGain=null,raf=0,last=0,current=-1,busy=false;
const duration=()=>clips.reduce((sum,c)=>sum+c.end-c.start,0);
const format=t=>{const ms=Math.max(0,Math.round((Number(t)||0)*1000));return `${Math.floor(ms/60000).toString().padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}.${String(ms%1000).padStart(3,'0')}`};
function status(s){$('status').textContent=s}
function locate(t){let offset=0;for(let i=0;i<clips.length;i++){const d=clips[i].end-clips[i].start;if(t<offset+d||i===clips.length-1)return {i,local:clips[i].start+Math.min(d,Math.max(0,t-offset))};offset+=d}return null}
function connect(v){if(!audioCtx)audioCtx=new AudioContext();if(!destination)destination=audioCtx.createMediaStreamDestination();const source=audioCtx.createMediaElementSource(v),gain=audioCtx.createGain();source.connect(gain);gain.connect(audioCtx.destination);gain.connect(destination);return gain}
function pause(){playing=false;cancelAnimationFrame(raf);clips.forEach(c=>c.video.pause());music?.video.pause();$('play').textContent='▶';$('play').setAttribute('aria-label','Reproduzir')}
function draw(){ctx.fillStyle='#090a0b';ctx.fillRect(0,0,canvas.width,canvas.height);const p=locate(time);if(p){const v=clips[p.i].video;if(v.readyState>=2){const scale=Math.min(canvas.width/v.videoWidth,canvas.height/v.videoHeight),w=v.videoWidth*scale,h=v.videoHeight*scale;ctx.drawImage(v,(canvas.width-w)/2,(canvas.height-h)/2,w,h)}}paintText(ctx,canvas,time);$('time').textContent=`${format(time)} / ${format(duration())}`;$('seek').value=time}
function paintText(ctx,canvas,time){const text=$('text').value.trim();if(text&&time>=+$('textStart').value&&time<+$('textEnd').value){const size=Math.max(16,Math.min(160,+$('fontSize').value||56))*canvas.width/1920;ctx.font=`700 ${size}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle=$('color').value;ctx.shadowColor='#000';ctx.shadowBlur=size*.16;const lines=text.split('\n'),gap=size*1.25;let y=$('position').value==='top'?canvas.height*.15:$('position').value==='bottom'?canvas.height*.82:canvas.height*.5;y-=(lines.length-1)*gap/2;lines.forEach((line,i)=>ctx.fillText(line,canvas.width/2,y+i*gap,canvas.width*.9));ctx.shadowBlur=0}}
function seekVideo(v,t){return new Promise((resolve,reject)=>{if(Math.abs(v.currentTime-t)<.0005&&v.readyState>=2){resolve();return}const timer=setTimeout(()=>{clean();reject(new Error('Não foi possível ler este ponto do vídeo.'))},10000);function clean(){clearTimeout(timer);v.removeEventListener('seeked',done);v.removeEventListener('error',fail)}function done(){clean();resolve()}function fail(){clean();reject(new Error('Não foi possível ler o ficheiro.'))}v.addEventListener('seeked',done);v.addEventListener('error',fail);v.currentTime=Math.max(0,t)})}
async function seek(t){pause();time=Math.max(0,Math.min(duration(),t));const p=locate(time);if(p){await seekVideo(clips[p.i].video,p.local);current=p.i}if(music)await seekVideo(music.video,time%music.video.duration);draw()}
async function play(){if(!clips.length||busy)return;if(time>=duration()-.02)time=0;busy=true;try{if(!audioCtx)audioCtx=new AudioContext();await audioCtx.resume();clips.forEach(c=>{if(!c.gain)c.gain=connect(c.video);c.gain.gain.value=c.volume});if(music){if(!musicGain)musicGain=connect(music.video);musicGain.gain.value=+$('musicVolume').value}const p=locate(time);current=p.i;await seekVideo(clips[current].video,p.local);await clips[current].video.play();if(music){await seekVideo(music.video,time%music.video.duration);await music.video.play()}playing=true;$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pausar');last=performance.now();raf=requestAnimationFrame(tick)}catch(e){pause();status(e.message);throw e}finally{busy=false}}
async function tick(){
 if(!playing)return;
 const c=clips[current];
 const offset=clips.slice(0,current).reduce((sum,c)=>sum+c.end-c.start,0);
 time=Math.min(duration(),offset+Math.max(0,Math.min(c.end,c.video.currentTime)-c.start));
 if(c.video.ended||c.video.currentTime>=c.end-.008){
  c.video.pause();
  if(current===clips.length-1){time=duration();draw();pause();return}
  current++;
  try{await seekVideo(clips[current].video,clips[current].start);await clips[current].video.play()}
  catch(e){status(e.message);pause();return}
 }
 if(!playing)return;
 draw();raf=requestAnimationFrame(tick);
}

function render(){const d=duration();$('count').textContent=`${clips.length} ${clips.length===1?'clip':'clips'}`;$('empty').hidden=clips.length>0;$('seek').max=d;$('timeline').replaceChildren();$('library').replaceChildren();clips.forEach((c,i)=>{const b=document.createElement('button');b.className='clip'+(i===selected?' active':'');b.style.flexGrow=Math.max(1,c.end-c.start);b.textContent=c.name;const s=document.createElement('span');s.textContent=`${i+1} · ${(c.end-c.start).toFixed(1)} s`;b.append(s);b.onclick=()=>{selected=i;render()};$('timeline').append(b);const a=document.createElement('div');a.className='asset';const thumb=document.createElement('video');thumb.src=c.url;thumb.muted=true;thumb.preload='metadata';const title=document.createElement('div');title.textContent=c.name;a.append(thumb,title);$('library').append(a)});if(!clips.length){$('timeline').innerHTML='<div class="timeline-empty">Os clips aparecem aqui, pela ordem do filme.</div>'; $('library').innerHTML='<div class="empty-small">Os teus vídeos começam aqui.<br>Importa um ou vários clips.</div>'}const c=clips[selected];$('selected').textContent=c?c.name:'Seleciona um clip na linha de tempo.';['trimStart','trimEnd'].forEach(id=>$(id).disabled=!c);$('trimStart').value=c?c.start.toFixed(3):'';$('trimEnd').value=c?c.end.toFixed(3):'';$('clipVolume').value=c?c.volume:1;['split','remove','left','right'].forEach(id=>$(id).disabled=!c);$('export').disabled=!clips.length;draw()}
function media(file,isAudio=false){return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),v=document.createElement(isAudio?'audio':'video');v.preload='auto';v.playsInline=true;const timer=setTimeout(()=>{URL.revokeObjectURL(url);reject(new Error('O ficheiro demorou demasiado a abrir.'))},20000);v.onloadeddata=()=>{clearTimeout(timer);if(!Number.isFinite(v.duration)||v.duration<=0){URL.revokeObjectURL(url);reject(new Error('Duração de ficheiro inválida.'));return}v.onloadeddata=null;resolve({video:v,url,name:file.name,start:0,end:v.duration,volume:1,file})};v.onerror=()=>{clearTimeout(timer);URL.revokeObjectURL(url);reject(new Error(`Formato não suportado: ${file.name}`))};v.src=url})}
$('files').onchange=async e=>{if(exporting)return;pause();status('A importar vídeos…');for(const f of e.target.files){try{const c=await media(f);clips.push(c);selected=clips.length-1;render();status(`${clips.length} clips prontos a editar`)}catch(err){status(err.message)}}e.target.value='';render();await seek(time)};
$('start').onclick=()=>$('files').click();$('play').onclick=()=>playing?pause():play().catch(()=>{});$('rewind').onclick=()=>seek(0).catch(e=>status(e.message));$('seek').oninput=e=>seek(+e.target.value).catch(err=>status(err.message));
$('applyTrim').onclick=async()=>{const c=clips[selected];if(!c)return;const a=+$('trimStart').value,b=Math.min(c.video.duration,+$('trimEnd').value);if(!Number.isFinite(a)||!Number.isFinite(b)||a<0||b>c.video.duration||b-a<.05){status('Define uma entrada anterior à saída, dentro da duração do clip.');render();return}pause();c.start=a;c.end=b;time=Math.min(time,duration());render();await seek(time);status('Corte aplicado.')};
$('remove').onclick=()=>{pause();const [c]=clips.splice(selected,1);c.video.pause();c.gain?.disconnect();URL.revokeObjectURL(c.url);selected=Math.min(selected,clips.length-1);time=Math.min(time,duration());render();seek(time).catch(e=>status(e.message))};
function move(dir){const to=selected+dir;if(to<0||to>=clips.length)return;pause();[clips[selected],clips[to]]=[clips[to],clips[selected]];selected=to;render();seek(time).catch(e=>status(e.message))}$('left').onclick=()=>move(-1);$('right').onclick=()=>move(1);
$('split').onclick=async()=>{pause();const p=locate(time);if(!p)return;const c=clips[p.i];if(p.local-c.start<.05||c.end-p.local<.05){status('Coloca o cursor no interior de um clip para o dividir.');return}try{const copy=await media(c.file);copy.start=p.local;copy.end=c.end;copy.volume=c.volume;c.end=p.local;clips.splice(p.i+1,0,copy);selected=p.i+1;render();status('Clip dividido. Podes cortar ou mover cada parte.')}catch(e){status(e.message)}};
$('clipVolume').oninput=e=>{const c=clips[selected];if(c){c.volume=+e.target.value;if(c.gain)c.gain.gain.value=c.volume}};
$('music').onchange=async e=>{if(!e.target.files[0])return;pause();try{const next=await media(e.target.files[0],true);if(music){music.video.pause();URL.revokeObjectURL(music.url);musicGain?.disconnect()}music=next;music.video.loop=true;musicGain=null;$('musicName').textContent=music.name;$('audio-track').textContent=music.name;$('audio-track').className='filled';status('Música adicionada. Repete-se até ao fim do filme.')}catch(err){status(err.message)}e.target.value=''};
$('musicVolume').oninput=e=>{if(musicGain)musicGain.gain.value=+e.target.value};$('removeMusic').onclick=()=>{music?.video.pause();if(music)URL.revokeObjectURL(music.url);musicGain?.disconnect();music=null;musicGain=null;$('musicName').textContent='MP3, WAV ou outro áudio compatível';$('audio-track').textContent='Adiciona uma banda sonora no painel à direita';$('audio-track').className=''};
['text','textStart','textEnd','fontSize','color','position'].forEach(id=>$(id).oninput=()=>{$('text-track').textContent=$('text').value||'O teu título, no momento certo';$('text-track').className=$('text').value?'filled':'';draw()});
window.addEventListener('beforeunload',e=>{if(clips.length){e.preventDefault();e.returnValue=''}});render();
